### ISSUE TITLE
Toolbar runs off screen on small screen sizes.

### ISSUE THREAD

**Issue by MichaelARoberts** [chmln/vue-wysiwyg#46]
I've had issues with the component running out of the container it's in on small screen sizes (Nexus 5,  Iphone 6s).
![wysiwyg](https://user-images.githubusercontent.com/11383977/36273249-ec90680e-1251-11e8-9b07-42fe577b2cb9.png)

Current solution is setting the .editr--toolbar to have a height of auto, and a flex-wrap value.
```css
.editr--toolbar {
    background: #f6f6f6;
    border-bottom: 1px solid #e4e4e4;
    position: relative;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    height: auto;
    flex-wrap: wrap;
}
```

However the separators between buttons break. I've disabled them with following rule as well.

```css
.editr--toolbar a.vw-btn-separator {
    width: 1px;
    margin: 0 10px;
    display: none;
}
```

![wysiwyg](https://user-images.githubusercontent.com/11383977/36273624-138048e8-1253-11e8-9bb5-6855ed542868.png)

Not sure if there is a better fix.
